- gongmoja/src/main/java/com/est/gongmoja/dto/ChatDto.java
> Crerated Dto folder and Chat dto

- gongmoja/src/main/java/com/est/gongmoja/dto/ChatDto.java
UserService와 StockService를 만들었습니다
> feat : Added UserService and StockService

- gongmoja/build.gradle
- gongmoja/src/main/java/com/est/gongmoja/config/PasswordConfig.java
- gongmoja/src/main/java/com/est/gongmoja/config/WebSecurityConfig.java
- gongmoja/src/main/java/com/est/gongmoja/controller/UserController.java
- gongmoja/src/main/java/com/est/gongmoja/dto/user/UserRegisterRequestDto.java
- gongmoja/src/main/java/com/est/gongmoja/jwt/JwtTokenFilter.java
- gongmoja/src/main/java/com/est/gongmoja/jwt/JwtTokenUtil.java
- gongmoja/src/main/java/com/est/gongmoja/repository/UserRepository.java
- gongmoja/src/main/java/com/est/gongmoja/service/UserService.java
> feat : jwtTokenUtils 구현 및 auth 관련 skeleton 생성

- gongmoja/src/main/java/com/est/gongmoja/exception/CustomException.java
- gongmoja/src/main/java/com/est/gongmoja/exception/ErrorCode.java
- gongmoja/src/main/java/com/est/gongmoja/exception/ExceptionManager.java
> feat : 예외처리 관련 코드 통일

- gongmoja/src/main/java/com/est/gongmoja/entity/NewsEntity.java
- gongmoja/src/main/java/com/est/gongmoja/service/CrawlingService.java
- gongmoja/src/main/java/com/est/gongmoja/service/NewsCrawlingService.java
NewsCrawlingService, NewsEntity 수정
어떤 변경 사항이 있나요?
> fix: NewsCrawlingService, NewsEntity 수정

- gongmoja/src/main/java/com/est/gongmoja/repository/NewsRepository.java
- gongmoja/src/main/java/com/est/gongmoja/service/NewsCrawlingService.java
NewsCrawlingData db에 저장
어떤 변경 사항이 있나요?
> feat: NewsCrawlingData db에 저장

- gongmoja/src/main/java/com/est/gongmoja/config/WebSecurityConfig.java
- gongmoja/src/main/java/com/est/gongmoja/controller/UserController.java
- gongmoja/src/main/java/com/est/gongmoja/dto/user/UserLoginRequestDto.java
- gongmoja/src/main/java/com/est/gongmoja/dto/user/UserLoginResponseDto.java
- gongmoja/src/main/java/com/est/gongmoja/dto/user/UserRegisterRequestDto.java
- gongmoja/src/main/java/com/est/gongmoja/entity/RefreshTokenEntity.java
- gongmoja/src/main/java/com/est/gongmoja/exception/ErrorCode.java
- gongmoja/src/main/java/com/est/gongmoja/jwt/JwtTokenFilter.java
- gongmoja/src/main/java/com/est/gongmoja/jwt/JwtTokenUtil.java
- gongmoja/src/main/java/com/est/gongmoja/repository/RefreshTokenRepository.java
- gongmoja/src/main/java/com/est/gongmoja/repository/UserRepository.java
- gongmoja/src/main/java/com/est/gongmoja/service/UserService.java
- gongmoja/src/main/resources/templates/main.html
- gongmoja/src/main/resources/templates/users/login.html
- gongmoja/src/main/resources/templates/users/register.html
> feat : 로그인 , 회원가입 로직 구현 & Jwt Filter 구현

- gongmoja/src/main/java/com/est/gongmoja/GongmojaApplication.java
- gongmoja/src/main/java/com/est/gongmoja/service/NewsCrawlingService.java
> Feat: NewsCrawl dateTime 수정, NewsEntity와 StockEntity매핑

- gongmoja/src/main/java/com/est/gongmoja/service/CrawlingService.java
> feat: 10분마다 크롤링 변경

- gongmoja/src/main/java/com/est/gongmoja/entity/SponsorEntity.java
- gongmoja/src/main/java/com/est/gongmoja/entity/StockEntity.java
- gongmoja/src/main/java/com/est/gongmoja/repository/SponsorRepository.java
Sponsor 관련 파일 생성
어떤 변경 사항이 있나요?
> feat: Sponsor repo 생성

- gongmoja/src/main/java/com/est/gongmoja/entity/CompetitionEntity.java
- gongmoja/src/main/java/com/est/gongmoja/repository/CompetitionRepository.java
- gongmoja/src/main/java/com/est/gongmoja/service/CompetitonCrawlingService.java
- gongmoja/src/main/java/com/est/gongmoja/service/CrawlingService.java
- gongmoja/src/main/java/com/est/gongmoja/service/SponsorService.java
경쟁률 관련 크롤링 코드를 기본 틀만 잡는 단계입니다.
미완성본입니다.
어떤 변경 사항이 있나요?
> feat: 경쟁률 크롤링 기초 구현

- gongmoja/build.gradle
- gongmoja/src/main/java/com/est/gongmoja/config/AppProperties.java
- gongmoja/src/main/java/com/est/gongmoja/config/WebSecurityConfig.java
- gongmoja/src/main/java/com/est/gongmoja/controller/api/SocialUserController.java
- gongmoja/src/main/java/com/est/gongmoja/entity/UserEntity.java
- gongmoja/src/main/java/com/est/gongmoja/jwt/CookieUtil.java
- gongmoja/src/main/java/com/est/gongmoja/jwt/JwtTokenFilter.java
- gongmoja/src/main/java/com/est/gongmoja/oauth2/CustomOAuth2UserService.java
- gongmoja/src/main/java/com/est/gongmoja/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
- gongmoja/src/main/java/com/est/gongmoja/oauth2/OAuth2SuccessHandler.java
- gongmoja/src/main/resources/templates/users/login.html
> feat : OAuth2 구현

- gongmoja/src/main/java/com/est/gongmoja/service/CalendarService.java
- gongmoja/src/main/resources/templates/calendar/calendar.html
calendar 일정 클릭시  공모주 상세 페이지로 이동하도록 합니다
어떤 변경 사항이 있나요?
> feat: calendar 일정 클릭시 페이지 이동 구현

- gongmoja/src/main/resources/templates/question/question_detail.html
> 질문목록 html 수정

- gongmoja/src/main/java/com/est/gongmoja/config/CustomLogoutHandler.java
- gongmoja/src/main/java/com/est/gongmoja/exception/ErrorCode.java
- gongmoja/src/main/java/com/est/gongmoja/jwt/CookieUtil.java
- gongmoja/src/main/java/com/est/gongmoja/jwt/JwtTokenFilter.java
- gongmoja/src/main/java/com/est/gongmoja/oauth2/OAuth2SuccessHandler.java
> fix : 소셜로그인 시 JSESSIONID 쿠키 남는 에러 

- gongmoja/build.gradle
- gongmoja/src/main/java/com/est/gongmoja/controller/UserController.java
- gongmoja/src/main/java/com/est/gongmoja/dto/user/UserForgotPasswordRequestDto.java
- gongmoja/src/main/java/com/est/gongmoja/dto/user/UserModifyPasswordRequestDto.java
- gongmoja/src/main/java/com/est/gongmoja/entity/Role.java
- gongmoja/src/main/java/com/est/gongmoja/entity/UserEntity.java
- gongmoja/src/main/java/com/est/gongmoja/oauth2/CustomOAuth2UserService.java
- gongmoja/src/main/java/com/est/gongmoja/repository/UserRepository.java
- gongmoja/src/main/java/com/est/gongmoja/service/MailService.java
- gongmoja/src/main/java/com/est/gongmoja/service/UserService.java
- gongmoja/src/main/resources/templates/temp-password.html
- gongmoja/src/main/resources/templates/users/forgot-password.html
> feat : email 통한 비밀번호 재발급 

- gongmoja/src/main/java/com/est/gongmoja/service/QuestionService.java
- 파일 업로드 경로 /media로 변경
어떤 변경 사항이 있나요?
> feat : 파일 업로드 경로 변경

- gongmoja/src/main/java/com/est/gongmoja/service/CrawlingService.java
상장일 데이터 크롤링 시 Null 값으로 들어가는 경우에 대한 예외처리 구현
어떤 변경 사항이 있나요?
> chore: ipoDate 예외처리

- gongmoja/src/main/resources/templates/index.html
클릭 이벤트를 위한 div id 변경
어떤 변경 사항이 있나요?
> fix: 스크롤 이벤트 div 변경

- gongmoja/src/main/java/com/est/gongmoja/controller/QuestionController.java
- gongmoja/src/main/resources/templates/chat/chat-room.html
- gongmoja/src/main/resources/templates/index.html
- gongmoja/src/main/resources/templates/mypage.html
- gongmoja/src/main/resources/templates/question/question_detail.html
- gongmoja/src/main/resources/templates/question/question_form.html
- gongmoja/src/main/resources/templates/question/question_list.html
- gongmoja/src/main/resources/templates/stock/stock.html
- 페이지 타이틀 추가
- footer 추가
- 파일 업로드 버튼 오류 수정
어떤 변경 사항이 있나요?
> style : 페이지 타이틀 및 footer 추가

- gongmoja/src/main/java/com/est/gongmoja/controller/UserController.java
- gongmoja/src/main/resources/templates/404.html
- gongmoja/src/main/resources/templates/500.html
- gongmoja/src/main/resources/templates/error.html
- gongmoja/src/main/resources/templates/index.html
- gongmoja/src/main/resources/templates/stock/stock.html
- gongmoja/src/main/resources/templates/users/modify-password.html
1. `modify-password.html` 
1. 사이드 메뉴, 탑 바 구현
2. 탑 바 프로필 userEntity 속성 추가
3. 인증받은 사용자만 접근 가능하도록
4. favicon 추가, 로고 폰트 적용
2. `index.html` : 크기 조정 및 태그 수정
3. js 코드 누락 파일 추가
어떤 변경 사항이 있나요?
> chore: 전체적인 요소 사이즈 수정

- gongmoja/src/main/java/com/est/gongmoja/service/CrawlingService.java
- gongmoja/src/main/java/com/est/gongmoja/service/GraphService.java
- gongmoja/src/main/java/com/est/gongmoja/service/NewsCrawlingService.java
- gongmoja/src/main/resources/templates/chat/chat-room.html
- gongmoja/src/main/resources/templates/stock/stock.html
feat: graphservice 시간오류 수정, stock상세페이지 채팅방 연결
어떤 변경 사항이 있나요?
> feat: graphservice 시간오류 수정, stock상세페이지 채팅방 연결

- gongmoja/src/main/resources/templates/chat/chat-room.html
- gongmoja/src/main/resources/templates/index.html
- gongmoja/src/main/resources/templates/mypage.html
- gongmoja/src/main/resources/templates/question/question_detail.html
- gongmoja/src/main/resources/templates/question/question_form.html
- gongmoja/src/main/resources/templates/question/question_list.html
- gongmoja/src/main/resources/templates/question/question_list_admin.html
- gongmoja/src/main/resources/templates/stock/stock.html
- gongmoja/src/main/resources/templates/users/modify-password.html
- 마이페이지 : admin인 경우 전체 문의내역, user인 경우 내 문의내역 버튼 활성화되는 기능 추가
- 마이페이지,문의게시판 : 카드 적용 및 버튼 크기 변경
- 비밀번호 수정페이지 : footer 추가
- 전체 페이지 : 화면 축소시 나타나는 검색모양 일괄 삭제
어떤 변경 사항이 있나요?
> feat : 마이페이지 버튼 ROLE 적용, 스타일 변경

- gongmoja/src/main/java/com/est/gongmoja/config/WebSecurityConfig.java
- gongmoja/src/main/java/com/est/gongmoja/controller/UserController.java
- gongmoja/src/main/java/com/est/gongmoja/exception/ErrorCode.java
- gongmoja/src/main/java/com/est/gongmoja/service/UserService.java
- gongmoja/src/main/resources/templates/mypage.html
> refactor : Security Configuration 로직 수정 + 비밀번호 변경 로직 보완

- gongmoja/src/main/java/com/est/gongmoja/dto/chat/ChatDataDto.java
- gongmoja/src/main/java/com/est/gongmoja/service/ChatService.java
- gongmoja/src/main/resources/templates/chat/chat-room.html
> fix : 날짜생성 & 관리자 채팅 형식 수정

- gongmoja/src/main/java/com/est/gongmoja/service/CrawlingService.java
- gongmoja/src/main/java/com/est/gongmoja/service/QuestionService.java
- gongmoja/src/main/resources/templates/question/question_detail.html
- gongmoja/src/main/resources/templates/question/question_form.html
-  파일 저장 경로 변경(내부 static ->외부 /static)
- 파일선택시 삭제 기능 추가
어떤 변경 사항이 있나요?
> feat :  파일 저장 경로 변경(내부 static ->외부 /static)

- gongmoja/src/main/java/com/est/gongmoja/service/QuestionService.java
- gongmoja/src/main/resources/templates/question/question_detail.html
- 파일업로드시에만 첨부파일 확인 가능하게 변경
어떤 변경 사항이 있나요?
> feat : 파일업로드시에만 첨부파일 확인 가능하게 변경

- gongmoja/src/main/java/com/est/gongmoja/controller/ChatController.java
- gongmoja/src/main/java/com/est/gongmoja/dto/chat/ChatDataDto.java
- gongmoja/src/main/java/com/est/gongmoja/service/ChatService.java
- gongmoja/src/main/java/com/est/gongmoja/service/QuestionService.java
- gongmoja/src/main/resources/templates/chat/chat-room.html
- gongmoja/src/main/resources/templates/question/question_detail.html
-유저 닉네임이 동일 할 시 채팅이 안되는 현상을 수정했습니다
어떤 변경 사항이 있나요?
> fix: 유저 닉네임 중복시 채팅 불가 현상 수정

- gongmoja/src/main/resources/templates/chat/chat-room.html
> fix: fixed chatroom loss issue

- gongmoja/src/main/java/com/est/gongmoja/config/WebSecurityConfig.java
- gongmoja/src/main/java/com/est/gongmoja/controller/UserController.java
- gongmoja/src/main/java/com/est/gongmoja/dto/user/UserRegisterRequestDto.java
- gongmoja/src/main/resources/templates/users/message.html
- gongmoja/src/main/resources/templates/users/register.html
> fix : 회원가입 로직 수정

- gongmoja/src/main/resources/templates/chat/chat-room.html
- gongmoja/src/main/resources/templates/chat/list.html
> fix: 채팅방 리다이렉트 문제 수정
